import = [ "~/.config/alacritty/themes/monokai_pro.toml" ]

[window]

# Window dimensions
dimensions = { columns = 0, lines = 0 }  # Default: columns = 0, lines = 0

# Padding
padding = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Dynamic padding
dynamic_padding = false  # Default: false

# Window decorations
decorations = "Full"  # Default: "Full"

# Opacity
opacity = 1.0  # Default: 1.0

# Blur (macOS/KDE Wayland only)
blur = false  # Default: false

# Window title
title = "Alacritty"  # Default: "Alacritty"

# Dynamic title
dynamic_title = true  # Default: true

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3


[font]

normal = { family = "SauceCodePro Nerd Font", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
# Font size in points
size = 11.25  # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

[colors]
transparent_background_colors = false  
draw_bold_text_with_bright_colors = false 

[bell]

# Visual bell animation effect
animation = "Linear"  # Default: "Linear"

# Duration of the visual bell flash in milliseconds
duration = 0  # Default: 0

# Visual bell animation color
color = "#ffffff"  # Default: "#ffffff"

# Command executed when the bell is rung
command = "None"  # Default: "None"

[selection]

# Characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"

# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = true 


[terminal]

# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste"  # Default: "OnlyCopy"

[mouse]

# Example: { mouse = "Left", action = "Paste" }
bindings = []

[hints]

#[[hints.enabled]]
# regex = "..."
# hyperlinks = true
# post_processing = true
# persist = false
# action = "..."
# command = "..."
# binding = { key = "...", mods = "...", mode = "..." }
# mouse = { mods = "...", enabled = true }


[keyboard]

# Examples
# { key = "Key", mods = "Modifiers", action = "Action" },
# { key = "Key", mods = "Modifiers", chars = "Characters to send" },
# ...
bindings = [
]
