" This must go here instead of qol/basic-mappings.vim, because the variable
" may be used by plugins
let mapleader = "\<Space>"


if &compatible
  set nocompatible
endif

if has('nvim')
  call plug#begin('~/.config/nvim/plugged')
  execute pathogen#infect('~/.config/nvim/unmanaged/{}')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }
  Plug 'neovimhaskell/haskell-vim'
else
  call plug#begin('~/.vim/plugged')
  execute pathogen#infect('~/.vim/unmanaged/{}')
  Plug 'Valloric/YouCompleteMe'
endif

Plug 'rking/ag.vim'
Plug 'robu3/vimongous'
Plug 'sirtaj/vim-openscad'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree'
Plug 'bling/vim-airline'
Plug 'majutsushi/tagbar'
Plug 'flazz/vim-colorschemes'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-surround'
Plug 'jacoby6000/vim-scala'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/syntastic'
Plug 'mileszs/ack.vim'
Plug 'godlygeek/tabular'
Plug 'tpope/vim-markdown'
Plug 'geverding/vim-hocon'
Plug 'tpope/vim-surround'
Plug 'rking/ag.vim'
Plug 'Yggdroot/indentLine'
Plug 'elzr/vim-json'
Plug 'vim-scripts/greplace.vim'
Plug 'kien/rainbow_parentheses.vim'
Plug 'gregsexton/matchtag'
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
" Plug 'ensime/ensime-vim'
Plug 'scrooloose/vim-slumlord'
Plug 'aklt/plantuml-syntax'
Plug 'scrooloose/vim-slumlord'
Plug 'uarun/vim-protobuf'
Plug 'xolox/vim-misc'
Plug 'AndrewRadev/sideways.vim'
Plug 'sbdchd/neoformat'
Plug 'numkil/ag.nvim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'wakatime/vim-wakatime'
Plug 'jacoby6000/vimport-sort'
Plug 'ndmitchell/ghcid', { 'rtp': 'plugins/nvim' }
Plug 'ktonga/vim-follow-my-lead'
Plug 'tpope/vim-unimpaired'
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}

call plug#end()

for f in split(glob('~/.config/nvim/qol/before/*.vim'), '\n')
    exe 'source' f
endfor

for f in split(glob('~/.config/nvim/plugin-confs/*.vim'), '\n')
    exe 'source' f
endfor

for f in split(glob('~/.config/nvim/qol/after/*.vim'), '\n')
    exe 'source' f
endfor

