local MapFuncs = require("lib.map_util")

vim.g.mapleader = " "

MapFuncs.nnoremap("<leader>/", "Remove search highlight", "<cmd>nohl<cr>")
MapFuncs.nnoremap("gD", "Go to definition", vim.lsp.buf.definition)
MapFuncs.nnoremap("K", "Show hover text", vim.lsp.buf.hover)
MapFuncs.nnoremap("gi", "Go to implementations", vim.lsp.buf.implementation)
MapFuncs.nnoremap("gr", "Show references", vim.lsp.buf.references)
MapFuncs.nnoremap("gds", "Show documentation", vim.lsp.buf.document_symbol)
MapFuncs.nnoremap("gws", "Show workspace symbol", vim.lsp.buf.workspace_symbol)
MapFuncs.nnoremap("<leader>cl", "Run codelens", vim.lsp.codelens.run)
MapFuncs.nnoremap("<leader>sh", "Show signature", vim.lsp.buf.signature_help)
MapFuncs.nnoremap("<leader>rn", "Rename", vim.lsp.buf.rename)
MapFuncs.nnoremap("<leader>f", "Format source", vim.lsp.buf.format)
MapFuncs.nnoremap("<leader>ca", "Show code actions", vim.lsp.buf.code_action)
MapFuncs.nnoremap("<leader>cl", "Show code code lenses", vim.lsp.codelens.run)
MapFuncs.nnoremap("<leader>aa", "Show all diagnostics", vim.diagnostic.setqflist)
MapFuncs.nnoremap("<leader>ae", "Show all errors", function()
  vim.diagnostic.setqflist({ severity = "E" })
end)
MapFuncs.nnoremap("<leader>aw", "Show all warnings", function()
  vim.diagnostic.setqflist({ severity = "W" })
end)
MapFuncs.nnoremap("<leader>d", "Show current buffer diagnostics", vim.diagnostic.setloclist)
MapFuncs.nnoremap("[c", "Go to previous diagnostic", function()
  vim.diagnostic.goto_prev({ wrap = false })
end)
MapFuncs.nnoremap("]c", "Go to next diagnostic", function()
  vim.diagnostic.goto_next({ wrap = false })
end)
